server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      #配置路由列表
      routes:
        - id: provider_route      #路由的ID，没有固定规则但要求唯一
          uri: lb://cloud-consul-provider   #匹配后提供服务的路由地址，根据服务名访问,lb表示后台使用负载均衡
          predicates:
            - Path=/user/**          #断言，路径相匹配的进行路由
            #当访问/user相关的请求，都会转发到服务名为cloud-consul-provider的服务上，并把路由拼接到后面，对外暴露统一的接口
            #如访问http://localhost:9527/user/get那么会转发到http://cloud-consul-provider/user/get

        - id: consumer_route
          uri: lb://cloud-consul-consumer
          predicates:
              - Path=/consumer/**

management:
  endpoints:
    web:
      exposure:
        #开启所有web端点暴露
        include: "*"
